On Error Resume Next

Set objArgs = WScript.Arguments

WorkbookPathRef = objArgs(0)
WorkbookSheetLayout = objArgs(1)
Columna = objArgs(2)

'WorkbookPathRef = "C:\ReporteRegulatorioRpa\Input\Refacturacion_regular_v2 junio 2025.xlsm"
'WorkbookSheetLayout = "GastoHidrocarburos"
'Columna = "IA"

'Genera un objeto de tipo Excel Application
Set objExcel = CreateObject("Excel.Application")

'Parámetro para indicar si se quiere visible la aplicación de Excel
objExcel.Application.Visible = False
'Evita movimiento de pantalla
objExcel.Application.ScreenUpdating = False
'Parámetro evitar mostrar pop ups de Excel
objExcel.Application.DisplayAlerts = False

'Abre libro Excel
Set objWorkbookPathRef = objExcel.Workbooks.Open(WorkbookPathRef, 0)
Set objWorkbookSheetRefL = objWorkbookPathRef.Worksheets(WorkbookSheetLayout)

' Contar las celdas con valor "XML" en la columna Columna
Set objRange = objWorkbookSheetRefL.Range(Columna & "2:" & Columna & objWorkbookSheetRefL.UsedRange.Rows.Count)
intCount = 0
For Each objCell In objRange
    If objCell.Value = "XML" Then
        intCount = intCount + 1
    End If
Next

' Ultima fila con datos columna A
intLastRow = objWorkbookSheetRefL.Cells(objWorkbookSheetRefL.Rows.Count, 1).End(-4162).Row - 1


' Guardar y cerrar el libro de refacturación
objWorkbookPathRef.Save
objWorkbookPathRef.Close
' Cerrar la aplicación de Excel
objExcel.Quit

'Devuelve el error en caso de
If Err.Number <> 0 Then
    ' Guardar y cerrar el libro de refacturación
    objWorkbookPathRef.Save
    objWorkbookPathRef.Close
    ' Cerrar la aplicación de Excel
    objExcel.Quit
    Msg = "Error was generated by " & Err.Source & ". " & Err.Description
    WScript.StdOut.WriteLine Msg
Else
    WScript.StdOut.WriteLine CStr(intCount)
End if