On Error Resume Next

Set objArgs = WScript.Arguments

WorkbookRefacturacion = objArgs(0)
WorkbookTDC = objArgs(1)


'WorkbookRefacturacion = "C:\ReporteRegulatorioRpa\Temp\Refacturacion_regular_v2.xlsm"
'WorkbookTDC = "C:\ReporteRegulatorioRpa\Temp\TipoCambio.xls"


'Genera un objeto de tipo Excel Application
Set objExcel = CreateObject("Excel.Application")

'Parámetro para indicar si se quiere visible la aplicación de Excel
objExcel.Application.Visible = False
'Evita movimiento de pantalla
objExcel.Application.ScreenUpdating = False
'Parámetro evitar mostrar pop ups de Excel
objExcel.Application.DisplayAlerts = False

WorkbookSheetRefacturacion = "TC"

'Abre libro Excel
Set objWorkbookPathRefacturacion = objExcel.Workbooks.Open(WorkbookRefacturacion, 0)
Set objWorkbookSheetRefacturacion = objWorkbookPathRefacturacion.Worksheets(WorkbookSheetRefacturacion)

'Abre libro Excel de tipo cambio
Set objWorkbookPathTDC = objExcel.Workbooks.Open(WorkbookTDC, 0)
Set objWorkbookSheetTDC = objWorkbookPathTDC.Worksheets(1)

valorBusqueda = "Información diaria"                 ' Valor a buscar

' === Buscar valor en la hoja ===
Set celda = objWorkbookSheetTDC.Cells.Find(valorBusqueda)

If Not celda Is Nothing Then
    fila = celda.Row
    If fila >= 1 Then
        objWorkbookSheetTDC.Range("A1:A" & fila).EntireRow.Delete
    End If
End If

' ultima fila con datos
ultimaFila = objWorkbookSheetRefacturacion.Cells(objWorkbookSheetRefacturacion.Rows.Count, 1).End(-4162).Row

' copiar datos de tipo cambio
objWorkbookSheetTDC.Range("A3:D" & objWorkbookSheetTDC.Cells(objWorkbookSheetTDC.Rows.Count, 1).End(-4162).Row).Copy
objWorkbookSheetRefacturacion.Cells(ultimaFila, 1).PasteSpecial -4163 ' -4163 es xlPasteValues

ultimaFilaFormat = objWorkbookSheetRefacturacion.Cells(objWorkbookSheetRefacturacion.Rows.Count, 1).End(-4162).Row

Set rng = objWorkbookSheetRefacturacion.Range("A" & ultimaFila & ":A" & ultimaFilaFormat)

' TextToColumns con ancho fijo (FixedWidth)
rng.TextToColumns rng, 1, 1, , , , , , , , Array(0, 4)
rng.TextToColumns rng, 1, 1, , , , , , , , Array(0, 3)

' Guardar y cerrar el libro
objWorkbookPathRefacturacion.Save
objWorkbookPathRefacturacion.Close

' Cerrar el libro de tipo cambio
objWorkbookPathTDC.Save
objWorkbookPathTDC.Close

objExcel.Quit

'Devuelve el error en caso de
If Err.Number <> 0 Then
    ' Cerrar la aplicación de Excel
    objExcel.Quit
    Msg = "Error was generated by " & Err.Source & ". " & Err.Description
    WScript.StdOut.WriteLine Msg
Else
    WScript.StdOut.WriteLine "Script executed successfully."
End if