On Error Resume Next

Set objArgs = WScript.Arguments

fecha = CDate(objArgs(0))
valorEUR_USD = objArgs(1)
valorEUR_MXN = objArgs(2)
valorGBP_USD = objArgs(3)
valorGBP_MXN = objArgs(4)
WorkbookRefacturacion = objArgs(5)

'Genera un objeto de tipo Excel Application
Set objExcel = CreateObject("Excel.Application")

'Parámetro para indicar si se quiere visible la aplicación de Excel
objExcel.Application.Visible = False
'Evita movimiento de pantalla
objExcel.Application.ScreenUpdating = False
'Parámetro evitar mostrar pop ups de Excel
objExcel.Application.DisplayAlerts = False

WorkbookSheetRefacturacion = "TC"

'Abre libro Excel
Set objWorkbookPathRefacturacion = objExcel.Workbooks.Open(WorkbookRefacturacion, 0)
Set objWorkbookSheetRefacturacion = objWorkbookPathRefacturacion.Worksheets(WorkbookSheetRefacturacion)

existe = False
fila = 2

Do While objWorkbookSheetRefacturacion.Cells(fila, 8).Value <> ""
    If CStr(objWorkbookSheetRefacturacion.Cells(fila, 8).Value) = CStr(fecha) Then
        existe = True
        Exit Do
    End If
    fila = fila + 1
Loop

If Not existe Then
    objWorkbookSheetRefacturacion.Cells(fila, 8).Value = fecha
    objWorkbookSheetRefacturacion.Cells(fila, 9).Value = valorEUR_USD
    objWorkbookSheetRefacturacion.Cells(fila, 10).Value = valorEUR_MXN
    objWorkbookSheetRefacturacion.Cells(fila, 11).Value = valorGBP_USD
    objWorkbookSheetRefacturacion.Cells(fila, 12).Value = valorGBP_MXN
End If

' Guardar y cerrar el libro
objWorkbookPathRefacturacion.Save
objWorkbookPathRefacturacion.Close

objExcel.Quit

'Devuelve el error en caso de
If Err.Number <> 0 Then
    ' Cerrar la aplicación de Excel
    objExcel.Quit
    Msg = "Error was generated by " & Err.Source & ". " & Err.Description
    WScript.StdOut.WriteLine Msg
Else
    WScript.StdOut.WriteLine "Script executed successfully."
End if