On Error Resume Next

' Argumentos: libro origen, libro destino
Set objArgs = WScript.Arguments

WorkBookPath = objArgs(0)
WorkBookName = objArgs(1)
MacroName = objArgs(2)

'WorkBookPath = "C:\ReporteRegulatorioRpa\Input\Refacturacion_regular_v2 junio 2025.xlsm"
'WorkBookName = "Refacturacion_regular_v2 junio 2025.xlsm"
'MacroName = "paso1_Formulas"
 
Set objExcel = CreateObject("Excel.Application")

'Parámetro para indicar si se quiere visible la aplicación de Excel
objExcel.Application.Visible = False
'Evita movimiento de pantalla
objExcel.Application.ScreenUpdating = False
'Parámetro evitar mostrar pop ups de Excel
objExcel.Application.DisplayAlerts = False
 
Set objWorkBookPath = objExcel.Workbooks.Open(WorkBookPath, 0)

' Ejecutar la macro
objExcel.Run "'" & WorkBookName & "'" & "!" & MacroName

' Guardar cambios y cerrar
objWorkBookPath.Save
objWorkBookPath.Close False
objExcel.Quit
 
If Err.Number <> 0 Then
    Msg = "Error was generated by " & Err.Source & ". " & Err.Description
    WScript.StdOut.WriteLine Msg
Else
    WScript.StdOut.WriteLine "Script executed successfully."
End If