On Error Resume Next

WorkbookPathConf = "Config.xlsx"

'Genera un objeto de tipo Excel Application
Set objExcel = CreateObject("Excel.Application")

'Parámetro para indicar si se quiere visible la aplicación de Excel
objExcel.Application.Visible = True
'Evita movimiento de pantalla
objExcel.Application.ScreenUpdating = True
'Parámetro evitar mostrar pop ups de Excel
objExcel.Application.DisplayAlerts = False

Set fso = CreateObject("Scripting.FileSystemObject")
' Ruta completa del script
scriptFullPath = WScript.ScriptFullName
' Solo la carpeta del script
scriptFolder = fso.GetParentFolderName(scriptFullPath)

scriptFolder = Replace(scriptFolder, ".scripts", "Data")

Set objWorkbookPathConfig = objExcel.Workbooks.Open(scriptFolder + "\" +WorkbookPathConf)
Set objWorkbookSheetConfig= objWorkbookPathConfig.Worksheets("Settings")

objWorkbookSheetConfig.Calculate

' Guardar y cerrar el libro de refacturación
objWorkbookPathConfig.Save
objWorkbookPathConfig.Close
' Cerrar la aplicación de Excel
objExcel.Quit

'Devuelve el error en caso de
If Err.Number <> 0 Then
    ' Guardar y cerrar el libro de refacturación
    objWorkbookPathConfig.Save
    objWorkbookPathConfig.Close

    ' Cerrar la aplicación de Excel
    objExcel.Quit
    Msg = "Error was generated by " & Err.Source & ". " & Err.Description
    WScript.StdOut.WriteLine Msg
Else
    WScript.StdOut.WriteLine "Script executed successfully."
End if